language: java
dist: trusty
jdk:
  - oraclejdk8
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c357408ecf80c245c3a3
    on_success: change
    on_failure: always
    on_start: never
